/* Remove the compiled-output and packaging dirs.
 *
 * `tsc` and the bundlers never delete output, so deleted `src/` modules leave stale `.js` behind
 * in `out/` that then ship in `app.asar` of every local package build (files is all-negation —
 * silence means ship). `out/` and `dist/` are both gitignored build products, so removing them is
 * always safe; they are regenerated by `build:desktop` / `electron-builder`.
 *
 * Cross-platform `rm -rf`: package.json scripts run under the host shell (cmd.exe on Windows), so
 * a POSIX `rm -rf` in the script string would not work. */

import { rmSync } from 'node:fs'
import { join, resolve } from 'node:path'

const PROJECT_ROOT = resolve(import.meta.dirname, '..')

for (const dir of ['out', 'dist']) {
  rmSync(join(PROJECT_ROOT, dir), { recursive: true, force: true })
}

console.log('cleaned out/ and dist/')
